language: python
dist: focal
python:
  - 3.6
  - 3.7
before_install:
  - pip install pipupgrade
  - pipupgrade --verbose --latest --yes
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
install:
  # Necessary since piwheels only provides packages for ARM and poetry locks them
  - rm -rf poetry.lock
  - head -n -3 pyproject.toml > pyproject.toml.new && cp pyproject.toml.new pyproject.toml
  - poetry install
  - npm install -g snyk
script: poetry build
jobs:
  include:
    - stage: code quality
      name: flake8
      script: poetry run flake8
    - stage: code quality
      name: flake8
      script: poetry run flake8
    - name: mypy
      script: poetry run mypy ./minigugl
    - stage: security scans
      name: safety
      script: poetry run safety check
    - name: bandit
      script: poetry run bandit -r ./minigugl
    - name: dodgy
      script: poetry run dodgy
    - name: snyk
      script:
        - snyk test --all-projects
        - snyk monitor --all-projects
