language: python
dist: focal
python:
  - 3.6
  - 3.7
before_install:
  - pip install pipupgrade
  - pipupgrade --verbose --latest --yes
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
install:
  - poetry install
  - npm install -g snyk
script:
  - poetry run safety check
  - poetry run bandit -r ./minigugl
  - poetry run dodgy
  - poetry run flake8
  - poetry run mypy ./minigugl
  - snyk test --all-projects
